#!/usr/bin/bash

# Analyze packet dumps generated by the arduino, when logging packets on serial out.

# Generate command histogram by frequency
grep command: dump.log | sort | uniq -c >summary.txt
echo "" >>summary.txt
grep source: dump.log | sort | uniq -c | sort -r >>summary.txt
echo "" >>summary.txt
grep target: dump.log | sort | uniq -c | sort -r >>summary.txt

cat summary.txt
